workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and regenerate iOS
        script: |
          rm -rf ios
          flutter create --platforms=ios .
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa